site_name: "RDEToolKit Documentation"
site_url: https://nims-mdpf.github.io/rdetoolkit/
theme:
  favicon: img/2585322.png
  logo: img/2585322.png
  name: "material"
  language: ja
  custom_dir: docs/overrides
  font:
    text: Noto Sans JP
  palette:
    - scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang: "ja"
  - i18n:
      languages:
        - locale: ja
          name: 日本語
          build: true
          default: true
          nav:
            - はじめに:
                - プロジェクト概要: README_ja.md
                - はじめに: index.ja.md
                - インストール: installation.md
                - クイックスタート: usage/quickstart.md
                - クイックスタート（詳細ガイド）: quick-start.ja.md
            - ユーザーガイド:
                - ガイド概要: user-guide/index.ja.md
                - 設定ガイド: user-guide/config.ja.md
                - 構造化処理ガイド: user-guide/structured-processing.ja.md
                - 構造化処理開発:
                    - 構造化プロセスの構築: usage/structured_process/structured.md
                    - 構造化処理開発ガイド: usage/structured_process/development_guide.md
                    - 対応ディレクトリ: usage/structured_process/directory.md
                    - ディレクトリパスアクセス: usage/structured_process/rdepath.md
                    - エラーハンドリング: usage/structured_process/errorhandling.md
                    - ログ出力: usage/logging.md
                    - LLM/AI向けトレースバック: usage/structured_process/traceback.md
                    - データタイル説明欄の自動転記: usage/structured_process/feature_description.md
                    - csvをグラフ化する: usage/structured_process/csv2graph.md
                    - csv2graphサンプル集: usage/structured_process/csv2graph_samples.md
                - データ登録モード:
                    - 利用可能なデータ登録モード: usage/mode/mode.md
                    - invoiceモード: usage/mode/mode_invoice.md
                    - ExcelInvoiceモード: usage/mode/mode_excelinvoice.md
                    - SmartTableInvoiceモード: usage/mode/mode_smarttableinvoice.md
                    - MultiDataTileモード: usage/mode/mode_multidatatile.md
                    - RDEFormatモード: usage/mode/mode_rdeformat.md
                - 設定ファイルとCLI:
                    - 設定ファイル: usage/config/config.md
                    - ファイル/フォルダモード: usage/config/file_folder_mode.md
                    - マジック変数: usage/config/magic_variable.md
                    - コマンドライン操作: usage/cli.md
                - テンプレートファイルと検証:
                    - テンプレートファイル: usage/metadata_definition_file.md
                    - データ検証: usage/validation.md
                - 統合:
                    - オブジェクトストレージ (MinIO): usage/object_storage.md
                    - Docker の使用: usage/docker.md
            - API リファレンス:
                - APIガイド: api/index.ja.md
                - 概要: rdetoolkit/index.md
                - コアモジュール:
                    - 設定: rdetoolkit/config.md
                    - コア機能: rdetoolkit/core.md
                    - ワークフロー: rdetoolkit/workflows.md
                    - モード処理: rdetoolkit/modeproc.md
                    - Invoiceファイル: rdetoolkit/invoicefile.md
                    - ユーティリティ: rdetoolkit/rde2util.md
                    - ロギング: rdetoolkit/rdelogger.md
                    - 代表画像操作: rdetoolkit/img2thumb.md
                    - CSVグラフ化: rdetoolkit/csv2graph.md
                    - 検証: rdetoolkit/validation.md
                    - 例外: rdetoolkit/exceptions.md
                    - エラーハンドリング: rdetoolkit/errors.md
                    - ファイル操作: rdetoolkit/fileops.md
                - 処理パイプライン:
                    - 概要: rdetoolkit/processing/index.md
                    - コンテキスト: rdetoolkit/processing/context.md
                    - ファクトリ: rdetoolkit/processing/factories.md
                    - パイプライン: rdetoolkit/processing/pipeline.md
                    - プロセッサ:
                        - 概要: rdetoolkit/processing/processors/index.md
                        - データセット: rdetoolkit/processing/processors/datasets.md
                        - 説明: rdetoolkit/processing/processors/descriptions.md
                        - ファイル: rdetoolkit/processing/processors/files.md
                        - 送り状: rdetoolkit/processing/processors/invoice.md
                        - サムネイル: rdetoolkit/processing/processors/thumbnails.md
                        - 検証: rdetoolkit/processing/processors/validation.md
                        - 変数: rdetoolkit/processing/processors/variables.md
                - トレースバック:
                    - 概要: rdetoolkit/traceback/index.md
                    - フォーマッター: rdetoolkit/traceback/formatter.md
                    - マスキング: rdetoolkit/traceback/masking.md
                - データモデル:
                    - 設定モデル: rdetoolkit/models/config.md
                    - Invoiceモデル: rdetoolkit/models/invoice.md
                    - Invoiceスキーマ: rdetoolkit/models/invoice_schema.md
                    - メタデータモデル: rdetoolkit/models/metadata.md
                    - タイプ定義: rdetoolkit/models/rde2types.md
                    - 結果出力: rdetoolkit/models/result.md
                    - レポートモデル: rdetoolkit/models/report.md
                - 実装:
                    - 圧縮: rdetoolkit/impl/compressed_controller.md
                    - 入力ファイル: rdetoolkit/impl/input_controller.md
                - インターフェース:
                    - ファイルチェック: rdetoolkit/interface/filechecker.md
                - コマンド:
                    - ベースコマンド: rdetoolkit/cmd/command.md
                    - アーカイブ生成: rdetoolkit/cmd/archive.md
                    - 設定ファイル生成: rdetoolkit/cmd/gen_config.md
                    - Excel形式Invoice生成: rdetoolkit/cmd/gen_excelinvoice.md
                - ストレージ:
                    - MinIO 統合: rdetoolkit/storage/minio.md
                - アーティファクト:
                    - レポート生成: rdetoolkit/artifact/report.md
            - コントリビューション:
                - 概要: development/index.md
                - ドキュメントへの貢献: development/docs.md
                - ソースコードへの貢献: development/contributing.md
                - ドキュメントワークフロー: contribute/documents_contributing.md
                - コントリビューションガイド: contribute/home.md
                - ソースコードワークフロー: contribute/sourcecode_contributing.md
        - locale: en
          name: English
          build: true
          nav:
            - Getting Started:
                - Project Overview (JA): README_ja.md
                - Introduction: index.en.md
                - Installation: installation.md
                - Quick Start: usage/quickstart.md
                - Detailed Quick Start: quick-start.en.md
            - User Guide:
                - Guide Overview: user-guide/index.en.md
                - Configuration Guide: user-guide/config.en.md
                - Structuring Processing Guide: user-guide/structured-processing.en.md
                - Structuring Processing:
                    - Building Structured Process: usage/structured_process/structured.md
                    - Development Guide: usage/structured_process/development_guide.md
                    - Supported Directories: usage/structured_process/directory.md
                    - Directory Path Access: usage/structured_process/rdepath.md
                    - Error Handling: usage/structured_process/errorhandling.md
                    - Logging: usage/logging.md
                    - LLM/AI-Friendly Traceback: usage/structured_process/traceback.md
                    - Feature Description: usage/structured_process/feature_description.md
                    - Visualizing CSV as Graphs: usage/structured_process/csv2graph.md
                    - csv2graph Sample Gallery: usage/structured_process/csv2graph_samples.md
                - Data Registration Modes:
                    - Available Data Registration Modes: usage/mode/mode.md
                    - Invoice Mode: usage/mode/mode_invoice.md
                    - ExcelInvoice Mode: usage/mode/mode_excelinvoice.md
                    - SmartTableInvoice Mode: usage/mode/mode_smarttableinvoice.md
                    - MultiDataTile Mode: usage/mode/mode_multidatatile.md
                    - RDEFormat Mode: usage/mode/mode_rdeformat.md
                - Configuration & CLI:
                    - Configuration Files: usage/config/config.md
                    - File/Folder Modes: usage/config/file_folder_mode.md
                    - Magic Variables: usage/config/magic_variable.md
                    - Command Line Interface: usage/cli.md
                - Templates & Validation:
                    - Template Files: usage/metadata_definition_file.md
                    - Data Validation: usage/validation.md
                - Integrations:
                    - Object Storage (MinIO): usage/object_storage.md
                    - Docker Usage: usage/docker.md
            - API Reference:
                - API Guide: api/index.en.md
                - Overview: rdetoolkit/index.md
                - Core Modules:
                    - Configuration: rdetoolkit/config.md
                    - Core Functions: rdetoolkit/core.md
                    - Workflows: rdetoolkit/workflows.md
                    - Mode Processing: rdetoolkit/modeproc.md
                    - Invoice Files: rdetoolkit/invoicefile.md
                    - Utilities: rdetoolkit/rde2util.md
                    - Logging: rdetoolkit/rdelogger.md
                    - Image Processing: rdetoolkit/img2thumb.md
                    - CSV to Graph: rdetoolkit/csv2graph.md
                    - Validation: rdetoolkit/validation.md
                    - Exceptions: rdetoolkit/exceptions.md
                    - Error Handling: rdetoolkit/errors.md
                    - File Operations: rdetoolkit/fileops.md
                - Processing Pipeline:
                    - Overview: rdetoolkit/processing/index.md
                    - Context: rdetoolkit/processing/context.md
                    - Factories: rdetoolkit/processing/factories.md
                    - Pipeline: rdetoolkit/processing/pipeline.md
                    - Processors:
                        - Overview: rdetoolkit/processing/processors/index.md
                        - Datasets: rdetoolkit/processing/processors/datasets.md
                        - Descriptions: rdetoolkit/processing/processors/descriptions.md
                        - Files: rdetoolkit/processing/processors/files.md
                        - Invoice: rdetoolkit/processing/processors/invoice.md
                        - Thumbnails: rdetoolkit/processing/processors/thumbnails.md
                        - Validation: rdetoolkit/processing/processors/validation.md
                        - Variables: rdetoolkit/processing/processors/variables.md
                - Traceback:
                    - Overview: rdetoolkit/traceback/index.md
                    - Formatter: rdetoolkit/traceback/formatter.md
                    - Masking: rdetoolkit/traceback/masking.md
                - Data Models:
                    - Configuration Models: rdetoolkit/models/config.md
                    - Invoice Models: rdetoolkit/models/invoice.md
                    - Invoice Schema: rdetoolkit/models/invoice_schema.md
                    - Metadata Models: rdetoolkit/models/metadata.md
                    - Type Definitions: rdetoolkit/models/rde2types.md
                    - Result Models: rdetoolkit/models/result.md
                    - Report Model: rdetoolkit/models/report.md
                - Implementation:
                    - Compressed Controller: rdetoolkit/impl/compressed_controller.md
                    - Input Controller: rdetoolkit/impl/input_controller.md
                - Interfaces:
                    - File Checker: rdetoolkit/interface/filechecker.md
                - Commands:
                    - Base Commands: rdetoolkit/cmd/command.md
                    - Archive Generation: rdetoolkit/cmd/archive.md
                    - Config Generation: rdetoolkit/cmd/gen_config.md
                    - Excel Invoice Generation: rdetoolkit/cmd/gen_excelinvoice.md
                - Storage:
                    - MinIO Integration: rdetoolkit/storage/minio.md
                - Artifacts:
                    - Report Generation: rdetoolkit/artifact/report.md
            - Contributing:
                - Overview: development/index.md
                - Documentation: development/docs.md
                - Source Code: development/contributing.md
                - Documentation Workflow: contribute/documents_contributing.md
                - Contribution Home: contribute/home.md
                - Source Contribution Workflow: contribute/sourcecode_contributing.md
  - autorefs:
      resolve_closest: true
  - mermaid2
  - mkdocstrings:
      handlers:
        python:
          paths: [src, .]
          options:
            show_source: false
            merge_init_into_class: true
            show_root_heading: true
            docstring_style: google
            show_if_no_docstring: true
            signature_crossrefs: true

watch:
  - src

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: colorful
      linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/nims-mdpf/rdetoolkit
repo_name: nims-mdpf/rdetoolkit

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nims-dpfc/rdetoolkit
  consent:
    title: Cookie consent
    description:
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.

extra_javascript:
  - https://unpkg.com/mermaid@10.9.0/dist/mermaid.min.js
