from collections.abc import Callable
from pathlib import Path
from typing import Any
from rdetoolkit.models.rde2types import RdeDatasetPaths
from rdetoolkit.runner.mode_resolver import ModeKind
from rdetoolkit.types import InputPaths, InvoiceData, RdeConfig

INVOICE_STEP_STRUCTURED: str
INVOICE_STEP_MAGIC: str
INVOICE_STEP_DESCRIPTION: str
INVOICE_STEPS: frozenset[str]

class InvoiceService:
    def __init__(self) -> None: ...
    def begin_run(self) -> None: ...
    def end_run(self) -> None: ...
    def backup(self, mode: ModeKind, *, data_root: Path, inputdata_path: Path, rawfiles: tuple[Path, ...] = ...) -> Path: ...
    def prepare_tile(self, mode: ModeKind, *, paths: InputPaths, invoice_dir: Path, iteration_index: int, invariant_invoice: InvoiceData | None, invoice_source: Path) -> tuple[InvoiceData | None, dict[str, Any] | None]: ...
    def invariant_invoice(self, mode: ModeKind, *, data_root: Path) -> InvoiceData | None: ...
    def apply_step(self, step: str, *, config: RdeConfig, dataset_paths: RdeDatasetPaths, feature_updater: Callable[[], None] | None = ...) -> None: ...

def invoice_source_for(mode: ModeKind, *, data_root: Path) -> Path: ...
def build_tile_dataset_paths(*, paths: InputPaths, out: Any, invoice_org: Path) -> RdeDatasetPaths: ...
def build_description_updater(dataset_paths: RdeDatasetPaths) -> Callable[[], None]: ...
