"""Invoice parsing facade for v2 domain workflows."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from rdetoolkit.fileops import readf_json
from rdetoolkit.invoicefile import ExcelInvoiceFile, InvoiceFile, SmartTableFile
from rdetoolkit.types import InvoiceData

if TYPE_CHECKING:
    from rdetoolkit.modes.smarttable import SmartTableInvoiceBuilder


def load_invoice(invoice_path: str | Path, *, schema_path: str | Path | None = None) -> InvoiceData:
    """Load a JSON invoice file into v2 ``InvoiceData``.

    Args:
        invoice_path: Path to ``invoice.json``.
        schema_path: Optional path to ``invoice.schema.json`` to retain on the
            facade payload for downstream validation.

    Returns:
        Parsed invoice data.

    Raises:
        FileNotFoundError: If ``invoice_path`` does not exist.
        ValueError: If the invoice root is not a JSON object.
    """
    path = Path(invoice_path)
    if not path.exists():
        msg = f"Invoice file does not exist: {path}"
        raise FileNotFoundError(msg)
    raw: Any = readf_json(path)
    if not isinstance(raw, dict):
        msg = "Invoice JSON root must be an object"
        raise ValueError(msg)
    schema = readf_json(Path(schema_path)) if schema_path is not None else None
    return InvoiceData(raw=raw, mode="invoice", schema=schema)


def open_invoice_file(invoice_path: str | Path, *, schema_path: str | Path | None = None) -> InvoiceFile:
    """Open a JSON invoice using the legacy invoicefile implementation.

    Args:
        invoice_path: Path to ``invoice.json``.
        schema_path: Optional validation schema path.

    Returns:
        Legacy ``InvoiceFile`` instance.
    """
    schema = Path(schema_path) if schema_path is not None else None
    return InvoiceFile(Path(invoice_path), schema_path=schema)


def open_excel_invoice(invoice_path: str | Path) -> ExcelInvoiceFile:
    """Open an Excel invoice using the legacy invoicefile implementation.

    Args:
        invoice_path: Path to an Excel invoice workbook.

    Returns:
        Legacy ``ExcelInvoiceFile`` instance.
    """
    return ExcelInvoiceFile(Path(invoice_path))


def open_smarttable(table_path: str | Path) -> SmartTableFile:
    """Open a SmartTable using the legacy invoicefile implementation.

    Args:
        table_path: Path to a SmartTable file.

    Returns:
        Legacy ``SmartTableFile`` instance.
    """
    return SmartTableFile(Path(table_path))


def build_excelinvoice_tile_invoice(
    *,
    excel_path: Path,
    invoice_org: Path,
    invoice_schema_path: Path,
    dist_path: Path,
    idx: int,
) -> InvoiceData:
    """Build one ExcelInvoice tile invoice by delegating to v1 overwrite.

    Args:
        excel_path: Excel invoice workbook path.
        invoice_org: Original run-level ``invoice.json`` path.
        invoice_schema_path: Invoice schema path.
        dist_path: Destination tile ``invoice.json`` path.
        idx: Zero-based Excel data row index.

    Returns:
        Parsed tile invoice data.
    """
    dist_path.parent.mkdir(parents=True, exist_ok=True)
    ExcelInvoiceFile.overwrite(
        ExcelInvoiceFile(excel_path),
        invoice_org,
        dist_path,
        invoice_schema_path,
        idx,
    )
    return load_invoice(dist_path, schema_path=invoice_schema_path)


def smarttable_invoice_builder() -> SmartTableInvoiceBuilder:
    """Return a fresh run-owned SmartTable invoice builder.

    The class lives in the mode layer, which imports the planner, which imports
    this package: the import is therefore deferred to call time so the mode may
    depend on the domain without the domain depending on the mode at import
    time.

    Returns:
        A builder that has not yet read any base invoice.
    """
    from rdetoolkit.modes.smarttable import SmartTableInvoiceBuilder  # noqa: PLC0415 -- breaks the modes -> runner -> domain import cycle

    return SmartTableInvoiceBuilder()


def build_smarttable_tile_invoice(
    *,
    smarttable_rowfile: Path,
    invoice_org: Path,
    invoice_schema_path: Path,
    dist_path: Path,
    builder: SmartTableInvoiceBuilder | None = None,
) -> tuple[InvoiceData, dict[str, Any] | None]:
    """Build one SmartTable tile invoice with the mode-owned builder.

    The builder also computes the row dictionary a v1 callback receives as
    ``RdeOutputResourcePath.smarttable_row_data``. It is **returned** rather
    than retained: before Session I-REVIEW-A it was stashed in a process-global
    dictionary keyed by data root, which a concurrent run on the same root
    could erase between preparation and the callback (reviews F1/R4).

    Args:
        smarttable_rowfile: Per-row SmartTable CSV generated by the checker.
        invoice_org: Original run-level ``invoice.json`` path.
        invoice_schema_path: Invoice schema path.
        dist_path: Destination tile ``invoice.json`` path.
        builder: Run-owned builder. Omitting it builds this tile with a
            private builder, which reads the base invoice for this call only.

    Returns:
        The parsed tile invoice data and the row dictionary for this tile,
        which is ``None`` when the row CSV carried no data row.
    """
    active = builder if builder is not None else smarttable_invoice_builder()
    row_data = active.build(
        rowfile=smarttable_rowfile,
        invoice_org=invoice_org,
        invoice_schema_path=invoice_schema_path,
        dist_path=dist_path,
        metadata_def_path=invoice_schema_path.parent / "metadata-def.json",
        metadata_path=_tile_metadata_path(dist_path),
    )
    return load_invoice(dist_path, schema_path=invoice_schema_path), row_data


def _tile_metadata_path(dist_path: Path) -> Path:
    """Return the ``meta/metadata.json`` of the tile owning ``dist_path``.

    v1 resolved this through ``ProcessingContext.metadata_path``, which is
    ``RdeOutputResourcePath.meta / "metadata.json"`` — the sibling of the
    tile's ``invoice`` directory.
    """
    return dist_path.parents[1] / "meta" / "metadata.json"
