import pandas as pd
from _typeshed import Incomplete
from pathlib import Path
from typing import Literal

class ExcelInvoiceFile:
    template_generator: Incomplete
    invoice_path: Incomplete
    dfexcelinvoice: Incomplete
    df_general: Incomplete
    df_specific: Incomplete
    def __init__(self, invoice_path: Path) -> None: ...
    @classmethod
    def _get_template_generator(cls) -> Incomplete: ...
    def read(self, *, target_path: Path | None = None) -> tuple[pd.DataFrame, pd.DataFrame | None, pd.DataFrame | None]: ...
    @classmethod
    def generate_template(cls, invoice_schema_path: str | Path, save_path: str | Path, file_mode: Literal['file', 'folder'] = 'file') -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]: ...
    def save(self, save_path: str | Path, *, invoice: pd.DataFrame | None = None, sheet_name: str = 'invoice_form', index: list[str] | None = None, header: list[str] | None = None) -> None: ...
    def overwrite(self, invoice_org: Path, dist_path: Path, invoice_schema_path: Path, idx: int) -> None: ...
    @staticmethod
    def check_intermittent_empty_rows(df: pd.DataFrame) -> None: ...
