from _typeshed import Incomplete
from collections.abc import Callable as Callable
from typing import Any

STATIC_DIR: Incomplete
EX_GENERALTERM: Incomplete
EX_SPECIFICTERM: Incomplete
MAGIC_VARIABLE_PATTERN: Incomplete
logger: Incomplete

def _ensure_pandas() -> Any: ...
def _ensure_openpyxl_styles() -> tuple[Any, Any, Any]: ...
def _ensure_openpyxl_utils() -> Any: ...
def _ensure_chardet() -> Any: ...
def _ensure_validation_error() -> type[Exception]: ...
def _ensure_logger() -> Callable[..., Any]: ...
