from collections.abc import Mapping, MutableMapping
from pathlib import Path
from rdetoolkit.exceptions import StructuredError as StructuredError
from rdetoolkit.fileops import readf_json as readf_json, writef_json as writef_json
from typing import Any

class RuleBasedReplacer:
    rules: dict[str, str]
    last_apply_result: dict[str, Any]
    def __init__(self, *, rule_file_path: str | Path | None = None) -> None: ...
    def load_rules(self, filepath: str | Path) -> None: ...
    def get_apply_rules_obj(self, replacements: Mapping[str, Any], source_json_obj: MutableMapping[str, Any] | None, *, mapping_rules: Mapping[str, str] | None = None) -> dict[str, Any]: ...
    def set_rule(self, path: str, variable: str) -> None: ...
    def write_rule(self, replacements_rule: dict[str, Any], save_file_path: str | Path) -> str: ...

def apply_default_filename_mapping_rule(replacement_rule: dict[str, Any], save_file_path: str | Path) -> dict[str, Any]: ...
