import pandas as pd
from _typeshed import Incomplete
from collections.abc import Callable as Callable
from pathlib import Path
from typing import Literal
from rdetoolkit.exceptions import StructuredError as StructuredError

SheetType = Literal["invoice", "general_term", "specific_term", "unknown"]

def read_excelinvoice(excelinvoice_filepath: Path | str) -> tuple[pd.DataFrame, pd.DataFrame | None, pd.DataFrame | None]: ...
def _process_invoice_sheet(df: pd.DataFrame) -> pd.DataFrame: ...
def _process_general_term_sheet(df: pd.DataFrame) -> pd.DataFrame: ...
def _process_specific_term_sheet(df: pd.DataFrame) -> pd.DataFrame: ...
def _identify_sheet_type(sh_name: str, df: pd.DataFrame) -> SheetType: ...
_SHEET_PROCESSORS: dict[SheetType, Callable[[pd.DataFrame], pd.DataFrame]]
def check_exist_rawfiles(dfexcelinvoice: pd.DataFrame, excel_rawfiles: list[Path]) -> list[Path]: ...
def check_exist_rawfiles_for_folder(dfexcelinvoice: pd.DataFrame, rawfiles_tpl: tuple) -> list: ...
