"""Smoke test for property-based testing infrastructure.

This test verifies that the property-based testing setup is working correctly.
"""

import pytest

hypothesis = pytest.importorskip("hypothesis")
from hypothesis import given

from tests.property.strategies import ascii_text, finite_floats, safe_filename_chars


@pytest.mark.property
@given(text=ascii_text)
def test_ascii_text_strategy(text: str) -> None:
    """Verify ASCII text strategy generates valid strings.

    Given: An ASCII text string generated by hypothesis
    When: We check its properties
    Then: It should only contain printable ASCII characters
    """
    assert isinstance(text, str)
    # All characters should be printable ASCII (codepoints 32-126)
    for char in text:
        codepoint = ord(char)
        assert 32 <= codepoint <= 126


@pytest.mark.property
@given(value=finite_floats)
def test_finite_floats_strategy(value: float) -> None:
    """Verify finite floats strategy generates valid numbers.

    Given: A finite float generated by hypothesis
    When: We check its properties
    Then: It should be a finite number (not NaN or infinity)
    """
    import math

    assert isinstance(value, float)
    assert math.isfinite(value)
    assert not math.isnan(value)
    assert not math.isinf(value)


@pytest.mark.property
@given(filename=safe_filename_chars)
def test_safe_filename_strategy(filename: str) -> None:
    """Verify safe filename strategy generates valid filenames.

    Given: A safe filename string generated by hypothesis
    When: We check its properties
    Then: It should not contain any filesystem-unsafe characters
    """
    assert isinstance(filename, str)
    assert len(filename) > 0
    assert len(filename) <= 255

    # Should not contain filesystem-unsafe characters
    unsafe_chars = '\\/:*?"<>|'
    for char in unsafe_chars:
        assert char not in filename
