[build]
rustflags = []

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-undefined", "-C", "link-arg=dynamic_lookup"]

[target.x86_64-unknown-linux-gnu]
rustflags = [
  "-L", "native=/usr/lib/x86_64-linux-gnu",
  "-l", "python3.11",
]

