name: Core Module

on:
  push:
    branches:
      - "*"
      - "!docs*"
      - "!doc*"
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python development headers
        run: sudo apt-get update && sudo apt-get install -y python3-dev

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Run check
        run: cargo check
      - name: Run test
        run: cargo test --no-default-features
      - name: Run clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python development headers
        run: sudo apt-get update && sudo apt-get install -y python3-dev

      - name: Set Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Run Test
        run: cargo test --no-default-features
